# =============================================================================
# 10b_alpha3_table_from_rds.R — Bilingual α3 table emission from cached RDS
#
# Standalone helper: reads `alpha3_results.rds` (from a previous successful
# run of 10_alpha3_estimation.R) and re-emits both `tab_alpha3_results_en.tex`
# and `tab_alpha3_results_ko.tex` without re-running the (heavy) HonestDiD-
# requiring main script. Use when `HonestDiD` is not installed in the current
# environment OR when only the bilingual table needs to be regenerated.
#
# Inputs:
#   _outputs_symmetric/alpha3_results.rds
#
# Outputs:
#   _outputs_symmetric/tab_alpha3_results_en.tex
#   _outputs_symmetric/tab_alpha3_results_ko.tex
#
# Plan: quality_reports/plans/velvet-frolicking-glade.md (Phase A4)
# =============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(fs)
  library(here)
})

out_dir <- here::here("scripts", "R", "_outputs_symmetric")
rds_path <- file.path(out_dir, "alpha3_results.rds")
stopifnot(fs::file_exists(rds_path))

alpha3 <- readRDS(rds_path)

# Reconstruct the combined grid that 10_alpha3_estimation.R line 578-585 builds.
combined_grid <- dplyr::bind_rows(
  alpha3$area_own_grid       |> dplyr::mutate(outcome = "area_own"),
  alpha3$opcost_exrent_grid  |> dplyr::mutate(outcome = "op_cost_ex_rent") |>
                                dplyr::select(own_bin, bw_id, h, estimate, std.error,
                                              p.value, n_obs, outcome),
  alpha3$offfarm_grid        |> dplyr::mutate(outcome = "off_farm_income") |>
                                dplyr::select(own_bin, bw_id, h, estimate, std.error,
                                              p.value, n_obs, outcome)
) |>
  dplyr::select(outcome, own_bin, bw_id, h, estimate, std.error, p.value, n_obs)

outcome_label_ko <- c(
  area_own         = "자작 면적 (m\\textsuperscript{2})",
  op_cost_ex_rent  = "농업경영비 (임차료 제외, 원)",
  off_farm_income  = "농외소득 (원)"
)
bin_label_ko <- c(
  "1_pure_tenant" = "1\\_순임차",
  "2_low_owner"   = "2\\_저소유",
  "3_mixed"       = "3\\_혼합",
  "4_high_owner"  = "4\\_고소유",
  "5_pure_owner"  = "5\\_순소유"
)

write_alpha3_table <- function(grid, lang, path) {
  con <- file(path, "w")
  on.exit(close(con))
  cat("% Auto-generated by 10b_alpha3_table_from_rds.R — do not edit by hand.\n", file = con)
  cat("% Wave 5 α3 outcome hierarchy: 3 outcomes × 5 bins × 3 bandwidths.\n", file = con)
  cat("\\begin{tabular}{lllrrr}\n", file = con)
  cat("\\toprule\n", file = con)
  header <- if (lang == "ko") "결과변수 & Bin & BW & 추정치 & SE & p \\\\\n"
            else              "Outcome & Bin & BW & Estimate & SE & p \\\\\n"
  cat(header, file = con)
  cat("\\midrule\n", file = con)
  for (i in seq_len(nrow(grid))) {
    row <- grid[i, ]
    outcome_disp <- if (lang == "ko" && !is.null(outcome_label_ko[[row$outcome]]))
                       outcome_label_ko[[row$outcome]]
                    else gsub("_", "\\\\_", row$outcome)
    bin_disp <- if (lang == "ko" && !is.null(bin_label_ko[[as.character(row$own_bin)]]))
                   bin_label_ko[[as.character(row$own_bin)]]
                else gsub("_", "\\\\_", as.character(row$own_bin))
    line <- sprintf("%s & %s & %s & %.2f & %.2f & %.3f \\\\\n",
                    outcome_disp, bin_disp, row$bw_id,
                    row$estimate, row$std.error, row$p.value)
    cat(line, file = con)
  }
  cat("\\bottomrule\n", file = con)
  cat("\\end{tabular}\n", file = con)
}

write_alpha3_table(combined_grid, "en", file.path(out_dir, "tab_alpha3_results_en.tex"))
write_alpha3_table(combined_grid, "ko", file.path(out_dir, "tab_alpha3_results_ko.tex"))
message("10b_alpha3_table_from_rds.R: tab_alpha3_results_{en,ko}.tex emitted from cached RDS.")
